Repository kit-kitHub/Facilities_Info-Frontend, pull requests merged in 2024-11, with the labels that each got.

#4 폰트 적용 문제 해결
  lib/main.dart
  pubspec.yaml
Labels: bug

#8 Actions Unit Test 에러 수정
  .github/workflows/test_for_android.yml
  .github/workflows/test_for_ios.yml
Labels: bug

#11 Webview flutter issue 해결
  .gitignore
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/main.dart
  lib/src/map.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#14 Global font 적용
  lib/main.dart
Labels: bug, enhancement

#12 Kang ji hyeock map 현재위치 정보 버튼 활성화
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/src/map.dart
  pubspec.yaml
Labels: bug, enhancement

#18 정보 페이지에서 정보 출력
  lib/SingleTone/deviceInfo.dart
  lib/main.dart
  lib/src/Info.dart
  pubspec.yaml
Labels: enhancement

#17 Kang ji hyeock patch 1 Search 폰트 적용
  lib/main.dart
  lib/src/search.dart
Labels: bug
